# Generated by Django 5.0.6 on 2024-09-16 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventer', '0006_gallery_category_gallery_media_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
