# Generated by Django 5.0.6 on 2024-09-24 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationElements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('url', models.CharField(max_length=255)),
                ('is_dropdown', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companer.navigationelements')),
            ],
            options={
                'verbose_name': 'Navigation Element',
                'verbose_name_plural': 'Navigation Elements',
                'ordering': ['name'],
            },
        ),
    ]
