# Generated by Django 5.0.6 on 2024-09-27 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagline', models.CharField(max_length=200)),
                ('video', models.FileField(upload_to='banner_videos/')),
                ('learn_more_link', models.URLField(max_length=255)),
                ('get_started_link', models.URLField(max_length=255)),
            ],
        ),
    ]
