# Generated by Django 5.0.6 on 2024-09-27 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companer', '0002_bannercontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Milestones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='milestone_images/')),
            ],
        ),
    ]
