# Generated by Django 5.0.6 on 2024-09-28 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companer', '0005_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=64)),
                ('client_image', models.ImageField(upload_to='testimonials/')),
                ('feedback', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('video', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VideoTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('video_url', models.URLField()),
                ('description', models.TextField()),
            ],
        ),
    ]
