# Generated by Django 5.0.6 on 2024-09-30 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companer', '0008_contact_newsletter_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
