# Generated by Django 5.0.6 on 2024-08-13 13:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_newpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='newpost',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='newpost',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
