# Generated by Django 5.0.6 on 2024-07-19 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_remove_auctionlisting_date_remove_bid_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='category',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='auctionPics/'),
        ),
    ]
