# Generated by Django 5.0.6 on 2024-07-23 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_bid_auction_alter_bid_bidder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='category',
            field=models.CharField(choices=[('FD', 'foodies'), ('GC', 'gucci'), ('SD', 'SANDWITCH')], default='FD', max_length=2),
        ),
    ]
