# Generated by Django 5.0.6 on 2024-07-24 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_auctionlisting_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='category',
            field=models.CharField(choices=[('GC', 'General Category'), ('BS', 'Broom Stick')], max_length=2),
        ),
    ]
