# Generated by Django 5.0.6 on 2024-07-24 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_auctionlisting_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='category',
            field=models.CharField(choices=[('FD', 'Foods'), ('ET', 'Entertainment'), ('LS', 'LifeStyle'), ('CL', 'Clothing'), ('HL', 'Halal Category'), ('DL', 'Daily Essentials'), ('TD', 'Trendings'), ('TE', 'Techno')], max_length=2),
        ),
    ]
